data:
  url: "https://archive.ics.uci.edu/ml/machine-learning-databases/00292/Wholesale%20customers%20data.csv"
  categorical_cols: ["Channel", "Region"]
  numeric_cols: ["Fresh", "Milk", "Grocery", "Frozen", "Detergents_Paper", "Delicassen"]

clustering:
  use_best_k: true
  n_clusters: 4

evaluation:
  max_clusters: 10
  gamma: 1.0
  penalty_alpha: 0.1
