clustering:
  use_best_k: true  # Si es true, se buscará el mejor k usando find_best_k
  n_clusters: 4     # Si use_best_k es false, este será el número de clusters

evaluation:
  max_clusters: 10
  gamma: 1.0
  penalty_alpha: 0.1  # Factor de penalización para valores altos de k
